theme: null
title: Daggerheart

defaults:
  -
    scope:
        baseurl: "/dh-wiki" 
        url: "https://geshura.github.io"
        path: ""
        type: "pages"
        values:
        layout: "default"

plugins:
  - jekyll-feed
